#! ./.Cargo.toml

[package]
name = "location-tracking-service"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "service_tracking"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.28.2", features = ["full"]}
dotenv = "0.15.0"
redis = "0.23.0"
cargo-test = "0.3.1"
cargo-check = {version = "0.2.2"}
rand = "0.8.5"
futures = "0.3.28"
geohash = "0.13.0"