// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::Queryable;
use serde::{Deserialize, Serialize};

pub mod atlas_driver_offer_bpp {

    #[derive(Queryable, Debug, Clone, Serialize, Deserialize)]
    pub struct Geometry {
        pub id: /* TODO: unknown type Bpchar */,
        pub region: String,
        pub geom: Option</* TODO: unknown type Nullable<Geometry> */>,
    }

}
