# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "crates/router_svc/src/schema.rs"
generate_missing_sql_type_definitions = false
filter = { only_tables = ["geometry"] }
custom_type_derives = ["diesel::query_builder::QueryId"]

[migrations_directory]
dir = "migrations"
