// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

pub mod atlas_driver_offer_bpp {
    use diesel::sql_types::*;
    use diesel::{
        deserialize::{self, FromSql},
        expression, Identifiable, Queryable, QueryableByName,
    };
    use postgis_diesel::{
        sql_types::*,
        types::{LineString, Point},
    };
    use serde::Serialize;

    #[derive(Queryable, QueryableByName, Debug)]
    pub struct GeometryT {
        #[diesel(sql_type = Text)]
        pub id: String,
        #[diesel(sql_type = Text)]
        pub region: String,
    }

    // use std::fmt;
    // impl fmt::Debug for GeometryT {
    //     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    //         // Format the other fields as needed
    //         write!(f, "GeometryT {{ id: {}, region: {} }}", self.id, self.region)
    //     }
    // }
}
