apiVersion: v1
kind: ConfigMap
metadata:
  name: location-tracking-service-bus-depot-geojson
  namespace: atlas
data:
  belghoria_depot.json: |-
    {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              88.3777598,
              22.6595576
            ],
            [
              88.3774863,
              22.6584735
            ],
            [
              88.3803884,
              22.6572656
            ],
            [
              88.3809034,
              22.6582458
            ],
            [
              88.3800826,
              22.6587111
            ],
            [
              88.3780924,
              22.6594388
            ],
            [
              88.3777598,
              22.6595576
            ]
          ]
        ]
      ]
    }
  garia_depot.json: |-
    {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              88.3778523,
              22.4668718
            ],
            [
              88.3778416,
              22.4660787
            ],
            [
              88.3779167,
              22.465873
            ],
            [
              88.378142,
              22.4658457
            ],
            [
              88.3783727,
              22.4657118
            ],
            [
              88.3787267,
              22.4654639
            ],
            [
              88.3788769,
              22.4656771
            ],
            [
              88.3789842,
              22.4667925
            ],
            [
              88.3778523,
              22.4668718
            ]
          ]
        ]
      ]
    }
  howrah_depot.json: |-
    {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              88.3348133,
              22.578093
            ],
            [
              88.3339175,
              22.5778503
            ],
            [
              88.3329948,
              22.5775086
            ],
            [
              88.3321365,
              22.577033
            ],
            [
              88.3331504,
              22.5764535
            ],
            [
              88.3337834,
              22.5769538
            ],
            [
              88.334014,
              22.576721
            ],
            [
              88.3344324,
              22.5761613
            ],
            [
              88.3346738,
              22.5764436
            ],
            [
              88.3349045,
              22.5764733
            ],
            [
              88.3347972,
              22.5770429
            ],
            [
              88.3348616,
              22.5779544
            ],
            [
              88.3348133,
              22.578093
            ]
          ]
        ]
      ]
    }
  kasba_depot.json: |-
    {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              88.3991385,
              22.5155853
            ],
            [
              88.3990365,
              22.5145892
            ],
            [
              88.4013003,
              22.5143117
            ],
            [
              88.4010214,
              22.5154812
            ],
            [
              88.4007907,
              22.5154465
            ],
            [
              88.3991385,
              22.5155853
            ]
          ]
        ]
      ]
    }
  lake_depot.json: |-
    {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              88.3532296,
              22.5072057
            ],
            [
              88.3531062,
              22.5072156
            ],
            [
              88.3531223,
              22.5067646
            ],
            [
              88.3536051,
              22.5056149
            ],
            [
              88.353884,
              22.5055604
            ],
            [
              88.3548389,
              22.5053225
            ],
            [
              88.3553861,
              22.50616
            ],
            [
              88.3551232,
              22.5063384
            ],
            [
              88.3545546,
              22.5067597
            ],
            [
              88.3541952,
              22.5069777
            ],
            [
              88.3539752,
              22.507285
            ],
            [
              88.3532296,
              22.5072057
            ]
          ]
        ]
      ]
    }
  maniktala_depot.json: |-
    {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              88.3971839,
              22.5797067
            ],
            [
              88.3970766,
              22.5791371
            ],
            [
              88.3969157,
              22.5780177
            ],
            [
              88.3976506,
              22.5778889
            ],
            [
              88.3979242,
              22.5778889
            ],
            [
              88.3982621,
              22.5798008
            ],
            [
              88.3978008,
              22.579677
            ],
            [
              88.3971839,
              22.5797067
            ]
          ]
        ]
      ]
    }
  nilgunge_depot.json: |-
    {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              88.412835,
              22.7632565
            ],
            [
              88.4124273,
              22.7626382
            ],
            [
              88.4114403,
              22.7602638
            ],
            [
              88.4132696,
              22.7599225
            ],
            [
              88.4142781,
              22.7628707
            ],
            [
              88.412835,
              22.7632565
            ]
          ]
        ]
      ]
    }
  paikpara_depot.json: |-
    {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              88.3794306,
              22.6173324
            ],
            [
              88.3793018,
              22.6164906
            ],
            [
              88.3794681,
              22.6164509
            ],
            [
              88.3804874,
              22.6161736
            ],
            [
              88.3813671,
              22.615936
            ],
            [
              88.3816032,
              22.6169065
            ],
            [
              88.3811901,
              22.6170006
            ],
            [
              88.3801655,
              22.6172928
            ],
            [
              88.3794306,
              22.6173324
            ]
          ]
        ]
      ]
    }
  pride_depot.json: |-
    {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              88.4614679,
              22.5832219
            ],
            [
              88.4612265,
              22.5822412
            ],
            [
              88.4631255,
              22.5818549
            ],
            [
              88.4633455,
              22.5829049
            ],
            [
              88.4614679,
              22.5832219
            ]
          ]
        ]
      ]
    }
  salt_lake_depot.json: |-
    {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              88.4286703,
              22.5802505
            ],
            [
              88.4288849,
              22.5799582
            ],
            [
              88.429314,
              22.5795025
            ],
            [
              88.4298397,
              22.5791112
            ],
            [
              88.4302313,
              22.5798047
            ],
            [
              88.4311379,
              22.5794084
            ],
            [
              88.4314598,
              22.5799632
            ],
            [
              88.431374,
              22.5800078
            ],
            [
              88.4305854,
              22.5804734
            ],
            [
              88.4300811,
              22.5810331
            ],
            [
              88.4286703,
              22.5802505
            ]
          ]
        ]
      ]
    }
  tartala_depot.json: |-
    {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              88.3054798,
              22.5157933
            ],
            [
              88.3052706,
              22.5148914
            ],
            [
              88.3049595,
              22.5136624
            ],
            [
              88.305748,
              22.513479
            ],
            [
              88.3063864,
              22.5157784
            ],
            [
              88.305689,
              22.5159172
            ],
            [
              88.3054798,
              22.5157933
            ]
          ]
        ]
      ]
    }
  thakurpur_depot.json: |-
    {
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [
              88.3101254,
              22.4747093
            ],
            [
              88.3099699,
              22.4733759
            ],
            [
              88.3105224,
              22.4735097
            ],
            [
              88.3116489,
              22.4734502
            ],
            [
              88.3117187,
              22.4748729
            ],
            [
              88.3101254,
              22.4747093
            ]
          ]
        ]
      ]
    }
